### ISSUE TITLE
Fixer la météo et les joueurs connectés sur le serveur avec des api différentes pour chaque serveurs

### ISSUE THREAD

**Issue by KvasirQc** [Izocel/Minecraft-Whitelist-Discord-Bot#19]

**Comment by Izocel** [comment]
Cest possible avec juste une api sur le proxie je crois...
________________________________
From: WeConnected ***@***.***>
Sent: Tuesday, October 18, 2022 12:30:45 AM
To: Izocel/Minecraft-Whitelist-Discord-Bot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Izocel/Minecraft-Whitelist-Discord-Bot] Fixer la météo et les joueurs connectés sur le serveur avec des api différentes pour chaque serveurs (Issue #19)

**Comment by Izocel** [comment]
ajouter au todo
