### ISSUE TITLE
Player already confirmed need to register again

### ISSUE THREAD

**Issue by KvasirQc** [Izocel/Minecraft-Whitelist-Discord-Bot#21]
Farkoza

![Screenshot_20221024-110056_Discord](https://user-images.githubusercontent.com/40178706/197559646-0c5e81dd-e672-4263-bba6-bac6a69ca5ba.jpg)

Sorry du trouble!

**Comment by KvasirQc** [comment]
![Screenshot_20221024-110548_Discord](https://user-images.githubusercontent.com/40178706/197560017-f0245461-9891-4c92-9e2d-ddc4e3c5fa3a.jpg)


Message recu auparavant

**Comment by Izocel** [comment]
dure a dire sans plus de détails on va voir si ça ce reproduit avec klkun d'autre qui pourra etre en mesure de décrire les step to reproduce de A à Z.

**Comment by Izocel** [comment]
dure a dire sans plus de détails on va voir si ça ce reproduit avec klkun d'autre qui pourra etre en mesure de décrire les step to reproduce de A à Z.
